import os
import json
import re
from typing import Dict, List, Optional, Any

# Knowledge Base grounding NVD, CWE, CAPEC datasets
# Incorporating paper fields and motivating examples

CVE_DATABASE = {
    "CVE-2021-45706": {
        "cve_id": "CVE-2021-45706",
        "description": "An issue was discovered in the zeroize_derive crate before 1.1.1 for Rust. A Rust data type does not properly zero memory after release due to improper memory release logic during unmapping or drop operations.",
        "cvss": 7.5,
        "affected_technology": "Rust zeroize_derive crate < 1.1.1",
        "source": "NVD (National Vulnerability Database)",
        "published_paper_example": True,
        "ground_truth_cwes": ["CWE-404", "CWE-772", "CWE-401"],
        "ground_truth_capecs": ["CAPEC-125", "CAPEC-130", "CAPEC-229", "CAPEC-230", "CAPEC-231", "CAPEC-491", "CAPEC-494", "CAPEC-495", "CAPEC-496", "CAPEC-666"]
    },
    "CVE-2021-44228": {
        "cve_id": "CVE-2021-44228",
        "description": "Apache Log4j2 2.0-beta9 through 2.15.0 JNDI features used in configuration, log messages, and parameters do not protect against attacker controlled LDAP and other JNDI related endpoints. An attacker who can control log messages or log message parameters can execute arbitrary code loaded from LDAP servers when message lookup substitution is enabled.",
        "cvss": 10.0,
        "affected_technology": "Apache Log4j 2.x",
        "source": "NVD (National Vulnerability Database)",
        "published_paper_example": False,
        "ground_truth_cwes": ["CWE-20", "CWE-502", "CWE-400"],
        "ground_truth_capecs": ["CAPEC-101", "CAPEC-248", "CAPEC-10"]
    },
    "CVE-2022-22965": {
        "cve_id": "CVE-2022-22965",
        "description": "A Spring MVC or Spring WebFlux application running on JDK 9+ may be vulnerable to remote code execution (RCE) via data binding. The vulnerability allows an attacker to exploit classloader manipulation through parameter binding.",
        "cvss": 9.8,
        "affected_technology": "Spring Framework < 5.3.18",
        "source": "NVD (National Vulnerability Database)",
        "published_paper_example": False,
        "ground_truth_cwes": ["CWE-20", "CWE-94"],
        "ground_truth_capecs": ["CAPEC-101", "CAPEC-242"]
    },
    "CVE-2021-3156": {
        "cve_id": "CVE-2021-3156",
        "description": "Sudo before 1.9.5p2 has a Heap-Based Buffer Overflow in alloc_argv() in sudoers.c via unescaped backslashes in command-line arguments during shell command parsing.",
        "cvss": 7.8,
        "affected_technology": "Sudo < 1.9.5p2",
        "source": "NVD (National Vulnerability Database)",
        "published_paper_example": False,
        "ground_truth_cwes": ["CWE-131", "CWE-122", "CWE-20"],
        "ground_truth_capecs": ["CAPEC-100", "CAPEC-47", "CAPEC-24"]
    },
    "CVE-2020-0601": {
        "cve_id": "CVE-2020-0601",
        "description": "A spoofing vulnerability exists in the way Windows CryptoAPI (Crypt32.dll) validates Elliptic Curve Cryptography (ECC) certificates. An attacker could exploit the vulnerability by using a spoofed code-signing certificate to sign a malicious executable.",
        "cvss": 8.1,
        "affected_technology": "Windows CryptoAPI",
        "source": "NVD (National Vulnerability Database)",
        "published_paper_example": False,
        "ground_truth_cwes": ["CWE-295", "CWE-347"],
        "ground_truth_capecs": ["CAPEC-473", "CAPEC-474"]
    },
    "CVE-2021-26855": {
        "cve_id": "CVE-2021-26855",
        "description": "Microsoft Exchange Server Server-Side Request Forgery (SSRF) Vulnerability allowing an unauthenticated attacker to authenticate as the Exchange server.",
        "cvss": 9.8,
        "affected_technology": "Microsoft Exchange Server 2013/2016/2019",
        "source": "NVD (National Vulnerability Database)",
        "published_paper_example": False,
        "ground_truth_cwes": ["CWE-918", "CWE-20"],
        "ground_truth_capecs": ["CAPEC-664", "CAPEC-228"]
    }
}

CWE_DATABASE = {
    "CWE-401": {
        "cwe_id": "CWE-401",
        "name": "Missing Release of Memory after Effective Lifetime",
        "description": "The software drives allocation of memory dynamically, but fails to release or free the allocated memory when it is no longer needed, leading to memory leaks or exposure.",
        "extended_description": "When memory is not properly released or zeroed after use, memory exhaustion can occur or sensitive residual data remains accessible in unallocated memory heaps or dropped frames.",
        "potential_mitigations": "Ensure all dynamically allocated memory is explicitly freed or scrubbed before reference destruction. Use RAII patterns or language constructs like Zeroize in Rust.",
        "background_details": "Commonly found in low-level memory management code, custom allocator implementations, and unsafe blocks in systems languages.",
        "alternate_terms": ["Memory Leak", "Unreleased Resource", "Uncleared Sensitive Heap"],
        "modes_of_introduction": ["Implementation", "Architecture and Design"],
        "common_consequences": ["Denial of Service (Resource Consumption)", "Confidentiality Breach (Heap Inspection)"],
        "detection_methods": ["Static Analysis", "Dynamic Memory Profiling (Valgrind, AddressSanitizer)"],
        "observed_examples": ["CVE-2021-45706 in Rust zeroize_derive"],
        "affected_resources": ["System Memory", "Process Heap"],
        "taxonomy_mappings": ["WSEC-401", "7 Pernicious Kingdoms: Unreleased Resource"],
        "notes": "Represented as a leaf weakness in VWC-MAP paper analysis for resource lifecycle bugs.",
        "relationships": {
            "ChildOf": ["CWE-772"],
            "CanPrecede": ["CWE-400"],
            "PeerOf": ["CWE-404"],
            "CanAlsoBe": ["CWE-459"],
            "CanFollow": ["CWE-704"]
        }
    },
    "CWE-772": {
        "cwe_id": "CWE-772",
        "name": "Missing Release of Resource after Effective Lifetime",
        "description": "The product does not release a resource after its effective lifetime has ended.",
        "extended_description": "When a resource is not released after usage, it remains unavailable for other tasks or leaks state into subsequent operations.",
        "potential_mitigations": "Use try-finally constructs or automatic resource management contexts.",
        "background_details": "Applies broadly to memory, file descriptors, network sockets, and database connections.",
        "alternate_terms": ["Resource Leak"],
        "modes_of_introduction": ["Implementation"],
        "common_consequences": ["Denial of Service"],
        "detection_methods": ["Static Code Analysis"],
        "observed_examples": ["CVE-2021-45706"],
        "affected_resources": ["System Resources"],
        "taxonomy_mappings": ["NVD CWE Class"],
        "notes": "Intermediate node in CWE hierarchy.",
        "relationships": {
            "ChildOf": ["CWE-404"],
            "CanPrecede": ["CWE-401"]
        }
    },
    "CWE-404": {
        "cwe_id": "CWE-404",
        "name": "Improper Resource Shutdown or Release",
        "description": "The program fails to release or improperly releases a system resource before termination or state change.",
        "extended_description": "Root class covering memory leaks, unclosed handles, socket exhaustion, and unzeroed security tokens.",
        "potential_mitigations": "Centralize resource destruction routines.",
        "background_details": "Root level weakness category in Research Concepts View.",
        "alternate_terms": ["Improper Cleanup"],
        "modes_of_introduction": ["Architecture and Design"],
        "common_consequences": ["Resource Exhaustion"],
        "detection_methods": ["Architecture Review"],
        "observed_examples": ["Multiple system kernel CVEs"],
        "affected_resources": ["Operating System Handles"],
        "taxonomy_mappings": ["MITRE Top 25"],
        "notes": "Root node in hierarchy (1,1,1) analysis.",
        "relationships": {
            "ChildOf": ["CWE-664"],
            "CanPrecede": ["CWE-772"]
        }
    },
    "CWE-20": {
        "cwe_id": "CWE-20",
        "name": "Improper Input Validation",
        "description": "The product receives input or data, but it does not validate or incorrectly validates that the input has the properties that are required to process the data safely and correctly.",
        "extended_description": "Input validation failures occur when application inputs are trusted without checking boundary conditions, syntax, length, or character encoding.",
        "potential_mitigations": "Use strict allow-lists, parameterized queries, and input sanitization libraries.",
        "background_details": "Ranked #4 in MITRE Most Dangerous Software Weaknesses.",
        "alternate_terms": ["Untrusted Input", "Missing Validation"],
        "modes_of_introduction": ["Implementation", "Architecture"],
        "common_consequences": ["Code Execution", "Bypass Security Controls", "Denial of Service"],
        "detection_methods": ["Automated Fuzzing", "Static Analysis", "Penetration Testing"],
        "observed_examples": ["CVE-2021-44228", "CVE-2022-22965"],
        "affected_resources": ["Application State", "Database", "System Memory"],
        "taxonomy_mappings": ["OWASP Top 10 A03:2021 Injection"],
        "notes": "Used in paper as a benchmark for T5 multi-command modeling ('One Weakness to Attack', 'Two Weakness to Attack').",
        "relationships": {
            "ChildOf": ["CWE-707"],
            "CanPrecede": ["CWE-119", "CWE-89", "CWE-79", "CWE-22"],
            "PeerOf": ["CWE-1284"]
        }
    },
    "CWE-22": {
        "cwe_id": "CWE-22",
        "name": "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
        "description": "The software uses external input to construct a pathname that should be within a restricted directory, but it does not properly sanitize sequences such as '../' that can resolve to a location outside of the restricted directory.",
        "extended_description": "Path traversal attacks aim to access files and directories stored outside the web root folder or arbitrary system paths.",
        "potential_mitigations": "Use canonical path resolution and verify that the target path begins with the allowed base directory.",
        "background_details": "Very common in web file managers, file serving APIs, and archive extraction.",
        "alternate_terms": ["Directory Traversal", "Dot-Dot-Slash"],
        "modes_of_introduction": ["Implementation"],
        "common_consequences": ["Read Files or Directories", "Execute Arbitrary Code"],
        "detection_methods": ["Static Analysis", "Web Application Scanners"],
        "observed_examples": ["CVE-2021-41773 Apache HTTP Server Path Traversal"],
        "affected_resources": ["File System"],
        "taxonomy_mappings": ["OWASP Top 10 A01:2021 Broken Access Control"],
        "notes": "Featured in paper Table II to showcase Link Prediction vs T5 text-to-text results.",
        "relationships": {
            "ChildOf": ["CWE-20"],
            "CanPrecede": ["CWE-73"],
            "CanAlsoBe": ["CWE-35"]
        }
    },
    "CWE-131": {
        "cwe_id": "CWE-131",
        "name": "Incorrect Calculation of Buffer Size",
        "description": "The software calculates the size of a buffer needed for an allocation, but the calculation produces an incorrect size, leading to buffer overflows or underflows.",
        "extended_description": "Often caused by integer overflows, missing null terminator room, character vs byte count confusion, or incorrect multiplication of array element sizes.",
        "potential_mitigations": "Use safe math functions (e.g., overflow checking multipliers) and standard container types.",
        "background_details": "Crucial weakness leading to memory safety vulnerabilities in C/C++/Rust unsafe code.",
        "alternate_terms": ["Allocation Size Mismatch", "Incorrect Length Compute"],
        "modes_of_introduction": ["Implementation"],
        "common_consequences": ["Memory Corruption", "Buffer Overflow"],
        "detection_methods": ["Static Analysis", "Compiler Warnings (-Wconversion)"],
        "observed_examples": ["CVE-2021-3156 in Sudo"],
        "affected_resources": ["Heap Memory", "Stack Memory"],
        "taxonomy_mappings": ["CWE Top 25"],
        "notes": "Featured in paper Table I comparing Link Prediction and T5 model predictions.",
        "relationships": {
            "ChildOf": ["CWE-682"],
            "CanPrecede": ["CWE-120", "CWE-122"]
        }
    }
}

CAPEC_DATABASE = {
    "CAPEC-125": {
        "capec_id": "CAPEC-125",
        "name": "Flooding",
        "description": "An adversary consumes resources of the target by sending large volumes of requests or data payloads, exhausting bandwidth, memory, or CPU.",
        "prerequisites": "Target service exposed to network or process invocation.",
        "mitigations": "Implement rate limiting, connection quotas, memory ceilings, and request throttling.",
        "alternate_terms": ["DoS Flooding", "Resource Exhaustion Attack"],
        "execution_flow": "1. Identify target endpoint. 2. Craft high volume request stream. 3. Trigger unreleased resource state.",
        "skills_required": "Low",
        "resources_required": "Network bandwidth or automated script.",
        "indicators": "Abnormal spike in unclosed connections or unallocated memory blocks.",
        "consequences": ["Denial of Service"],
        "example_instances": ["Exploiting memory release failure (CVE-2021-45706) to crash process."],
        "notes": "Predicted by VWC-MAP for CWE-401 / CVE-2021-45706.",
        "relationships": {"ChildOf": ["CAPEC-469"], "CanPrecede": ["CAPEC-130"]}
    },
    "CAPEC-130": {
        "capec_id": "CAPEC-130",
        "name": "Excessive Allocation",
        "description": "An adversary causes the target to allocate excessive quantities of memory or resources relative to the input provided.",
        "prerequisites": "Access to API accepting variable length or nested parameters.",
        "mitigations": "Enforce strict allocation bounds and max object size limits.",
        "alternate_terms": ["Memory Amplification"],
        "execution_flow": "1. Submit payload requesting large buffer. 2. Observe process memory growth.",
        "skills_required": "Medium",
        "resources_required": "Crafted payload.",
        "indicators": "Rapid RAM utilization growth per HTTP request.",
        "consequences": ["Process Crash", "Denial of Service"],
        "example_instances": ["Rust zeroize heap accumulation"],
        "notes": "VWC-MAP paper motivating example CAPEC.",
        "relationships": {"ChildOf": ["CAPEC-125"]}
    },
    "CAPEC-229": {
        "capec_id": "CAPEC-229",
        "name": "Serialized Data Parameter Blowup",
        "description": "An adversary supplies serialized data containing recursive structures or huge arrays that expand immensely during deserialization.",
        "prerequisites": "Deserialization mechanism enabled.",
        "mitigations": "Restrict deserialization depth and memory allocations during object inflation.",
        "alternate_terms": ["Billion Laughs Attack", "Deserialization Blowup"],
        "execution_flow": "1. Construct compressed/nested serialized stream. 2. Send to endpoint. 3. Cause memory leak.",
        "skills_required": "Medium",
        "resources_required": "Custom serializer tool.",
        "indicators": "High CPU and RAM footprint during JSON/XML/Bincode parse.",
        "consequences": ["Unchecked Resource Consumption"],
        "example_instances": ["Rust zeroize derive crate deserialization unzeroed struct"],
        "notes": "Associated with CWE-401 in VWC-MAP evaluation.",
        "relationships": {"PeerOf": ["CAPEC-230"]}
    },
    "CAPEC-230": {
        "capec_id": "CAPEC-230",
        "name": "Serialized Data with Nested Payloads",
        "description": "An adversary injects deeply nested data payloads into serialized object channels to exhaust stack or heap memory without freeing sub-objects.",
        "prerequisites": "Parser supports nested structures.",
        "mitigations": "Limit depth of parse trees.",
        "alternate_terms": ["Nested Object Bomb"],
        "execution_flow": "1. Generate 1000-deep nested array. 2. Post to server.",
        "skills_required": "Low",
        "resources_required": "Payload script.",
        "indicators": "Stack overflow trace or unhandled memory drop exception.",
        "consequences": ["Denial of Service"],
        "example_instances": ["Rust struct nesting drop failure"],
        "notes": "VWC-MAP paper result for Rust memory leak.",
        "relationships": {"ChildOf": ["CAPEC-229"]}
    },
    "CAPEC-231": {
        "capec_id": "CAPEC-231",
        "name": "Oversized Serialized Data Payloads",
        "description": "Sending oversized payloads through serialized channels causing memory buffers to leak during partial parse failure handling.",
        "prerequisites": "Endpoint accepting serialized inputs.",
        "mitigations": "Strict content length checks before buffer allocation.",
        "alternate_terms": ["Oversized Stream Attack"],
        "execution_flow": "1. Send large binary payload. 2. Abort connection mid-stream.",
        "skills_required": "Low",
        "resources_required": "Netcat script.",
        "indicators": "Orphaned allocated memory handles.",
        "consequences": ["Resource Exhaustion"],
        "example_instances": ["CVE-2021-45706 memory leakage"],
        "notes": "VWC-MAP result.",
        "relationships": {"PeerOf": ["CAPEC-230"]}
    },
    "CAPEC-491": {
        "capec_id": "CAPEC-491",
        "name": "Quadratic Data Expansion",
        "description": "Exploiting algorithm complexity in data expansion routines to trigger O(N^2) memory or time consumption.",
        "prerequisites": "Compression or string expansion routine.",
        "mitigations": "Cap expansion factor ratios.",
        "alternate_terms": ["Quadratic Blowup"],
        "execution_flow": "1. Pass input triggering expansion loop. 2. Observe resource saturation.",
        "skills_required": "Medium",
        "resources_required": "Expansion payload.",
        "indicators": "Exponential memory allocation growth.",
        "consequences": ["Denial of Service"],
        "example_instances": ["Zeroize derive memory copy"],
        "notes": "Paper result for CVE-2021-45706.",
        "relationships": {"CanPrecede": ["CAPEC-125"]}
    },
    "CAPEC-494": {
        "capec_id": "CAPEC-494",
        "name": "TCP Fragmentation",
        "description": "An adversary sends fragmented TCP packets forcing the OS to hold fragment buffers in memory without releasing them.",
        "prerequisites": "Network access to TCP listening service.",
        "mitigations": "Configure fragment timeout limits and max fragment queues.",
        "alternate_terms": ["Teardrop Attack", "TCP Reassembly Exhaustion"],
        "execution_flow": "1. Send incomplete fragments. 2. Never send final fragment.",
        "skills_required": "High",
        "resources_required": "Raw socket driver.",
        "indicators": "TCP reassembly queue saturated.",
        "consequences": ["Network Stack Crash"],
        "example_instances": ["Memory lifecycle failure in network stack"],
        "notes": "VWC-MAP paper identified CAPEC for unreleased memory patterns.",
        "relationships": {"PeerOf": ["CAPEC-495"]}
    },
    "CAPEC-495": {
        "capec_id": "CAPEC-495",
        "name": "UDP Fragmentation",
        "description": "Crafting malformed UDP fragments to exhaust reassembly buffers.",
        "prerequisites": "UDP port accessible.",
        "mitigations": "Drop out-of-order UDP fragments.",
        "alternate_terms": ["UDP Buffer Flooding"],
        "execution_flow": "1. Flood UDP fragments with overlapping offsets.",
        "skills_required": "Medium",
        "resources_required": "Packet generator.",
        "indicators": "UDP buffer kernel memory leak.",
        "consequences": ["Denial of Service"],
        "example_instances": ["Kernel memory leak"],
        "notes": "Paper result.",
        "relationships": {"PeerOf": ["CAPEC-494"]}
    },
    "CAPEC-496": {
        "capec_id": "CAPEC-496",
        "name": "ICMP Fragmentation",
        "description": "Exploiting ICMP packet reassembly logic to leave memory buffers unfreed.",
        "prerequisites": "ICMP allowed through firewall.",
        "mitigations": "Filter large ICMP messages.",
        "alternate_terms": ["Ping of Death / ICMP Leak"],
        "execution_flow": "1. Send fragmented ICMP Echo requests.",
        "skills_required": "Low",
        "resources_required": "Ping utility.",
        "indicators": "ICMP pool exhausted.",
        "consequences": ["System Freeze"],
        "example_instances": ["Buffer unfreeing"],
        "notes": "Paper result.",
        "relationships": {"PeerOf": ["CAPEC-495"]}
    },
    "CAPEC-666": {
        "capec_id": "CAPEC-666",
        "name": "BlueSmacking",
        "description": "Sending oversized L2CAP packets over Bluetooth to trigger unreleased buffer condition in wireless protocol stacks.",
        "prerequisites": "Bluetooth proximity.",
        "mitigations": "Update Bluetooth stack firmware.",
        "alternate_terms": ["Bluetooth DoS"],
        "execution_flow": "1. Pair or ping target via Bluetooth L2CAP. 2. Overflow ping payload.",
        "skills_required": "Medium",
        "resources_required": "Bluetooth adapter.",
        "indicators": "Wireless daemon restart loop.",
        "consequences": ["Wireless Crash"],
        "example_instances": ["Bluetooth driver unreleased memory"],
        "notes": "VWC-MAP paper result for unreleased memory patterns across hardware/software interfaces.",
        "relationships": {"ChildOf": ["CAPEC-125"]}
    },
    "CAPEC-100": {
        "capec_id": "CAPEC-100",
        "name": "Overflow Buffers",
        "description": "An adversary provides input that exceeds the allocated size of a target buffer, overwriting adjacent memory spaces.",
        "prerequisites": "Target function performs write operations without verifying bounds against buffer size.",
        "mitigations": "Use safe string/memory functions (strncpy, snprintf) and compiler defenses (ASLR, Stack Canaries).",
        "alternate_terms": ["Buffer Overflow", "Memory Overwrite"],
        "execution_flow": "1. Find input field mapped to fixed array. 2. Craft input larger than allocated size. 3. Hijack execution control.",
        "skills_required": "High",
        "resources_required": "Debugger (GDB) and exploit development framework.",
        "indicators": "Segmentation fault or EIP register override.",
        "consequences": ["Arbitrary Code Execution", "System Compromise"],
        "example_instances": ["CVE-2021-3156 Sudo heap overflow"],
        "notes": "Featured in Table I for CWE-131 evaluation (Rating 10/10). Ground truth in paper.",
        "relationships": {"ChildOf": ["CAPEC-125"], "CanPrecede": ["CAPEC-14"]}
    },
    "CAPEC-47": {
        "capec_id": "CAPEC-47",
        "name": "Buffer Overflow via Parameter Expansion",
        "description": "An adversary supplies input parameters containing shell syntax or macro expansions that enlarge significantly during evaluation, overflowing static destination buffers.",
        "prerequisites": "Target application performs expansion of parameters into fixed-size buffer.",
        "mitigations": "Validate post-expansion parameter length before copying to destination memory.",
        "alternate_terms": ["Macro Expansion Overflow"],
        "execution_flow": "1. Submit payload with variable expansion markers. 2. Trigger string expansion routine.",
        "skills_required": "Medium",
        "resources_required": "Custom parameter payload.",
        "indicators": "Process crash during string concatenation.",
        "consequences": ["Code Execution"],
        "example_instances": ["Parameter expansion in command line parsers"],
        "notes": "Table I paper prediction for CWE-131 (Rating 10/10). Ground truth in paper.",
        "relationships": {"ChildOf": ["CAPEC-100"]}
    },
    "CAPEC-14": {
        "capec_id": "CAPEC-14",
        "name": "Client-side Injection-induced Buffer Overflow",
        "description": "Injecting client-side parameters that force local buffer overflows in client software or web extensions.",
        "prerequisites": "Client application processing untrusted remote data.",
        "mitigations": "Sanitize server responses in client memory handlers.",
        "alternate_terms": ["Client Buffer Overflow"],
        "execution_flow": "1. Serve crafted response to client. 2. Overflow client buffer.",
        "skills_required": "Medium",
        "resources_required": "Malicious web server.",
        "indicators": "Browser crashes.",
        "consequences": ["Client Execution"],
        "example_instances": ["Browser plugin buffer overflow"],
        "notes": "Table I paper prediction for CWE-131 (Rating 8/10).",
        "relationships": {"ChildOf": ["CAPEC-100"]}
    },
    "CAPEC-24": {
        "capec_id": "CAPEC-24",
        "name": "Filter Failure through Buffer Overflow",
        "description": "An adversary overflows an input filtering buffer, causing input validation logic to crash or be bypassed entirely.",
        "prerequisites": "Filter routine uses internal fixed-size buffer.",
        "mitigations": "Separate input validation routines from target application buffers.",
        "alternate_terms": ["Filter Bypass via Memory Corruption"],
        "execution_flow": "1. Send long string to filter. 2. Overflow filter state. 3. Pass malicious payload uninspected.",
        "skills_required": "High",
        "resources_required": "Exploit payload.",
        "indicators": "Filter daemon crash logs.",
        "consequences": ["Bypass Defense"],
        "example_instances": ["WAF buffer overflow bypass"],
        "notes": "Table I prediction for CWE-131 (Rating 10/10).",
        "relationships": {"CanPrecede": ["CAPEC-100"]}
    },
    "CAPEC-126": {
        "capec_id": "CAPEC-126",
        "name": "Path Traversal",
        "description": "An adversary uses special sequence characters like '../' to escape restricted file directories and access unauthorized files on the server.",
        "prerequisites": "Application takes filename parameter without sanitization.",
        "mitigations": "Enforce strict allowlists for filenames and resolve canonical absolute paths.",
        "alternate_terms": ["Directory Traversal", "Relative Path Manipulation"],
        "execution_flow": "1. Locate file view endpoint. 2. Input `../../../../etc/passwd`. 3. Read sensitive files.",
        "skills_required": "Low",
        "resources_required": "Web browser or curl.",
        "indicators": "HTTP requests containing `../` or `%2e%2e%2f`.",
        "consequences": ["Confidentiality Leak", "File Disclosure"],
        "example_instances": ["Path traversal in web servers"],
        "notes": "Featured in Table II for CWE-22 (Ground truth, Rating 10/10).",
        "relationships": {"ChildOf": ["CAPEC-125"], "CanPrecede": ["CAPEC-64"]}
    },
    "CAPEC-64": {
        "capec_id": "CAPEC-64",
        "name": "Using Slashes and URL Encoding Combined to Bypass Validation Logic",
        "description": "Combining forward slashes, backslashes, double URL encoding (%252e%252e%252f), and unicode to evade naive string matching filters.",
        "prerequisites": "Validation filter performs single-pass URL decoding.",
        "mitigations": "Decode input completely before validating canonical paths.",
        "alternate_terms": ["Double URL Encoding Traversal"],
        "execution_flow": "1. Encode `../` as `%252e%252e%252f`. 2. Submit to target. 3. Target decodes once to `%2e%2e%2f` passing filter, then decodes again during file open.",
        "skills_required": "Low",
        "resources_required": "URL encoder tool.",
        "indicators": "Multiple `%` symbols in path parameters.",
        "consequences": ["Validation Bypass"],
        "example_instances": ["CVE-2021-41773 Apache HTTP Server"],
        "notes": "Table II prediction for CWE-22 (Rating 10/10 in T5).",
        "relationships": {"ChildOf": ["CAPEC-126"]}
    },
    "CAPEC-76": {
        "capec_id": "CAPEC-76",
        "name": "Manipulating Web Input to File System Calls",
        "description": "Directly injecting file path control characters into web form parameters passed to open(), read(), or include() calls.",
        "prerequisites": "Web parameters directly used in file system API calls.",
        "mitigations": "Use indirect mapping tables (indexes) instead of direct filenames.",
        "alternate_terms": ["File Ingestion Attack"],
        "execution_flow": "1. Identify parameter used in `fopen()`. 2. Supply file path.",
        "skills_required": "Low",
        "resources_required": "Browser dev tools.",
        "indicators": "System file paths in GET query string.",
        "consequences": ["Unauthorized Data Read"],
        "example_instances": ["PHP file inclusion vulnerabilities"],
        "notes": "Table II prediction for CWE-22 (Ground truth, Rating 10/10).",
        "relationships": {"PeerOf": ["CAPEC-126"]}
    },
    "CAPEC-101": {
        "capec_id": "CAPEC-101",
        "name": "Server Side Include (SSI) Injection",
        "description": "An adversary injects Server Side Include directives into HTML pages or web forms to execute arbitrary system commands when parsed by web servers.",
        "prerequisites": "SSI parsing enabled on web server.",
        "mitigations": "Disable SSI execution or escape user input before rendering.",
        "alternate_terms": ["SSI Injection"],
        "execution_flow": "1. Submit `<!--#exec cmd=\"ls\" -->`. 2. Server executes command during response construction.",
        "skills_required": "Low",
        "resources_required": "HTTP client.",
        "indicators": "HTML response containing shell command output.",
        "consequences": ["Remote Code Execution"],
        "example_instances": ["CVE-2021-44228 Log4j JNDI injection variant"],
        "notes": "Used in paper Figure 2 as example for T5 model command 'Two Weakness to Attack: CWE-20'.",
        "relationships": {"ChildOf": ["CAPEC-125"]}
    },
    "CAPEC-10": {
        "capec_id": "CAPEC-10",
        "name": "Buffer Overflow via Environment Variables",
        "description": "An adversary sets malicious, oversized environment variables before executing a binary with elevated privileges, triggering a buffer overflow.",
        "prerequisites": "Local executable inherits unvalidated environment variables.",
        "mitigations": "Sanitize and limit length of all environment variables in setuid binaries.",
        "alternate_terms": ["Env Var Overflow"],
        "execution_flow": "1. Export MAX_PATH string to env. 2. Launch setuid program.",
        "skills_required": "Medium",
        "resources_required": "Local terminal access.",
        "indicators": "Local privilege escalation crash dumps.",
        "consequences": ["Privilege Escalation"],
        "example_instances": ["Sudo env var buffer overflow"],
        "notes": "Used in Figure 2 for T5 command 'One Weakness to Attack: CWE-20'.",
        "relationships": {"ChildOf": ["CAPEC-100"]}
    }
}

# Ground truth relationships matrix from MITRE & Paper evaluation dataset
CWE_CAPEC_GROUND_TRUTH = {
    "CWE-401": ["CAPEC-125", "CAPEC-130", "CAPEC-229", "CAPEC-230", "CAPEC-231", "CAPEC-491", "CAPEC-494", "CAPEC-495", "CAPEC-496", "CAPEC-666"],
    "CWE-772": ["CAPEC-125", "CAPEC-130"],
    "CWE-404": ["CAPEC-125"],
    "CWE-20": ["CAPEC-10", "CAPEC-101", "CAPEC-24", "CAPEC-126", "CAPEC-64"],
    "CWE-22": ["CAPEC-126", "CAPEC-64", "CAPEC-76", "CAPEC-78", "CAPEC-79", "CAPEC-80", "CAPEC-139", "CAPEC-597", "CAPEC-3"],
    "CWE-131": ["CAPEC-100", "CAPEC-47", "CAPEC-14", "CAPEC-24", "CAPEC-45", "CAPEC-46", "CAPEC-8"]
}
