"use client";

import React, { useState, useEffect } from "react";
import { FlaskConical, Play, CheckCircle2, ShieldAlert, Database, ArrowRight, Info, AlertCircle } from "lucide-react";

export default function ResearchDemoView() {
  const [demos, setDemos] = useState<any[]>([]);
  const [selectedDemo, setSelectedDemo] = useState<any>(null);
  const [livePredictions, setLivePredictions] = useState<any>(null);
  const [isRunning, setIsRunning] = useState(false);

  useEffect(() => {
    fetchDemos();
  }, []);

  const fetchDemos = async () => {
    try {
      const res = await fetch("http://127.0.0.1:8000/api/demo-examples");
      const data = await res.json();
      setDemos(data);
      if (data.length > 0) {
        setSelectedDemo(data[0]);
        runLiveModel(data[0].cve_id);
      }
    } catch (err) {
      console.error("Demo API fallback", err);
    }
  };

  const runLiveModel = async (query: string) => {
    setIsRunning(true);
    try {
      const res = await fetch("http://127.0.0.1:8000/api/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, method: "t5" })
      });
      const data = await res.json();
      setLivePredictions(data);
    } catch (err) {
      console.error("Live analysis fallback", err);
    } finally {
      setIsRunning(false);
    }
  };

  return (
    <div className="space-y-8 pb-12">
      {/* Header */}
      <div className="cyber-card p-6 md:p-8 rounded-2xl border border-slate-800 space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-950 border border-cyan-800 text-cyan-300 text-xs font-mono mb-2">
              <FlaskConical className="h-3.5 w-3.5 text-cyan-400" />
              Paper Benchmark Pipeline Demonstration
            </div>
            <h2 className="text-2xl font-bold text-white">VWC-MAP Research Paper Demonstration</h2>
            <p className="text-xs text-slate-300 font-mono mt-1 max-w-2xl">
              Execution pipeline based on motivating examples from the 2022 IEEE HST paper. Compare Published Paper Results directly against Live Model Predictions.
            </p>
          </div>
        </div>

        {/* Demo Selector Tabs */}
        <div className="flex flex-wrap gap-2 pt-2 border-t border-slate-800/80">
          {demos.map((d) => (
            <button
              key={d.id}
              onClick={() => {
                setSelectedDemo(d);
                runLiveModel(d.cve_id);
              }}
              className={`px-4 py-2 rounded-lg text-xs font-mono font-semibold transition-all border ${
                selectedDemo?.id === d.id
                  ? "bg-gradient-to-r from-cyan-950 to-blue-950 text-cyan-300 border-cyan-500 shadow-lg shadow-cyan-500/10"
                  : "bg-slate-900 text-slate-400 border-slate-800 hover:text-white"
              }`}
            >
              <div className="flex items-center gap-2">
                <Play className="h-3.5 w-3.5 text-cyan-400" />
                {d.title}
              </div>
            </button>
          ))}
        </div>
      </div>

      {selectedDemo && (
        <div className="space-y-6">
          {/* Motivating Context Banner */}
          <div className="cyber-card p-6 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <span className="text-xs font-mono font-bold text-cyan-400 uppercase">Scenario Description</span>
              <span className="text-xs font-mono px-2.5 py-0.5 rounded bg-slate-900 text-slate-300 border border-slate-800">
                {selectedDemo.cve_id}
              </span>
            </div>
            <p className="text-xs text-slate-200 font-sans leading-relaxed">{selectedDemo.description}</p>
          </div>

          {/* Research Honesty Disclaimer (Section 41 & 18) */}
          <div className="p-4 rounded-xl bg-slate-900/90 border border-slate-700/80 text-xs font-mono text-slate-300 flex items-start gap-3">
            <Info className="h-5 w-5 text-cyan-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-white block font-bold mb-0.5">Research Honesty & Methodology Labeling</strong>
              <p className="text-slate-400 leading-normal text-[11px]">
                Below we explicitly separate <span className="text-cyan-400 font-bold">Published Paper Result</span> (the exact experimental findings recorded in the research paper) from <span className="text-purple-400 font-bold">Our Model Prediction</span> (live inferences generated by our configured ML pipeline).
              </p>
            </div>
          </div>

          {/* Side-by-Side Comparison Grid (Section 18) */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Left Column: Published Paper Result */}
            <div className="cyber-card p-6 rounded-2xl border border-cyan-800/80 space-y-4 bg-slate-950/80">
              <div className="flex items-center justify-between border-b border-cyan-900/80 pb-3">
                <h3 className="text-sm font-mono font-bold text-cyan-400 uppercase tracking-wider flex items-center gap-2">
                  <CheckCircle2 className="h-4 w-4 text-cyan-400" />
                  Published Paper Result
                </h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                  Ground Truth Reference
                </span>
              </div>

              <div className="space-y-4">
                <div>
                  <span className="text-xs font-mono font-bold text-slate-400 block mb-2">Paper Identified CWEs:</span>
                  <div className="flex flex-wrap gap-2">
                    {selectedDemo.paper_results.published_cwes.map((cwe: string) => (
                      <span key={cwe} className="px-2.5 py-1 rounded bg-purple-950 text-purple-300 border border-purple-800 font-mono text-xs font-bold">
                        {cwe}
                      </span>
                    ))}
                  </div>
                </div>

                <div>
                  <span className="text-xs font-mono font-bold text-slate-400 block mb-2">Paper Identified CAPEC Attack Patterns:</span>
                  <div className="grid grid-cols-2 gap-2 text-xs font-mono">
                    {selectedDemo.paper_results.published_capecs.map((capec: string) => (
                      <div key={capec} className="p-2 rounded bg-slate-900 border border-slate-800 text-emerald-300 font-semibold">
                        {capec}
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Right Column: Our Model Prediction */}
            <div className="cyber-card p-6 rounded-2xl border border-purple-800/80 space-y-4 bg-slate-950/80">
              <div className="flex items-center justify-between border-b border-purple-900/80 pb-3">
                <h3 className="text-sm font-mono font-bold text-purple-400 uppercase tracking-wider flex items-center gap-2">
                  <Database className="h-4 w-4 text-purple-400" />
                  Our Model Prediction
                </h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-purple-950 text-purple-300 border border-purple-800">
                  Live ML Inference
                </span>
              </div>

              {isRunning ? (
                <div className="py-12 text-center text-xs font-mono text-slate-400 space-y-2">
                  <div className="animate-spin text-purple-400 text-lg">●</div>
                  <p>Running Live Pipeline Model Inferences...</p>
                </div>
              ) : livePredictions ? (
                <div className="space-y-4">
                  <div>
                    <span className="text-xs font-mono font-bold text-slate-400 block mb-2">Live Predicted CWEs:</span>
                    <div className="space-y-2">
                      {livePredictions.cwe_predictions?.map((cwe: any) => (
                        <div key={cwe.cwe_id} className="p-2.5 rounded bg-slate-900 border border-slate-800 flex items-center justify-between text-xs font-mono">
                          <span className="font-bold text-purple-300">{cwe.cwe_id}: {cwe.name}</span>
                          <span className="text-emerald-400 font-bold">{Math.round(cwe.confidence * 100)}%</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  <div>
                    <span className="text-xs font-mono font-bold text-slate-400 block mb-2">Live Predicted CAPECs:</span>
                    <div className="grid grid-cols-2 gap-2 text-xs font-mono">
                      {livePredictions.capec_predictions?.slice(0, 6).map((capec: any) => (
                        <div key={capec.capec_id} className="p-2 rounded bg-slate-900 border border-slate-800 text-emerald-400 font-semibold truncate">
                          {capec.capec_id}: {capec.name}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              ) : (
                <p className="text-xs font-mono text-slate-500">Run live prediction pipeline.</p>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
